services:
  - type: web
    name: job-alert-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port=$PORT
    branch: main

  - type: worker
    name: daily-email-job
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    branch: main
