name: Daily Job Alert Email

on:
  schedule:
    - cron: '0 7 * * *'   # Runs daily at 7 AM UTC (12:30 PM IST)
  workflow_dispatch:       # Manual trigger option

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run main.py script
      env:
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      run: python main.py
